name = "SPHtoGrid"
uuid = "8a806948-229a-4117-b79b-c12ac366026f"
version = "0.6.0"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]

[deps]
Cosmology = "76746363-e552-5dba-9a5a-cef6fa9cc5ab"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffusiveShockAccelerationModels = "66fc4661-a670-4cc2-b407-bfd81989e880"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
GadgetIO = "826b50da-1eb7-48f3-bd4b-d2350582c309"
GadgetUnits = "08630afb-492b-4c1a-9729-2a116101b53a"
Healpix = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SPHKernels = "54ab9b88-2582-4358-b400-8014666a1730"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SynchrotronKernel = "7c311715-997f-43ba-a0ee-db1ccfe8d7f2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
Cosmology = "1"
DelimitedFiles = "1"
DiffusiveShockAccelerationModels = "0.1"
Distances = "0.10"
Documenter = "0.25, 0.26, 0.27, 1"
DocumenterTools = "0.1"
Downloads = "1"
FFTW = "1.10.0"
FITSIO = "0.16, 0.17"
GadgetIO = "0.5, 0.6, 0.7, 0.8"
GadgetUnits = "0.2, 0.3, 0.4, 0.5, 0.6"
Healpix = "4"
Interpolations = "0.15"
NearestNeighbors = "0.4"
PrecompileTools = "1"
ProgressMeter = "1"
QuadGK = "2"
Rotations = "1"
SPHKernels = "2"
SpecialFunctions = "0.1, 1, 2"
Statistics = "1"
SynchrotronKernel = "0.2"
Unitful = "1"
WriteVTK = "1"
julia = "1.7"
